spring:
  application:
    name: Trip
  config:
    import: security-variable.yml
    thymeleaf:
      cache: false
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/trip?serverTimezone=Asia/Seoul
      username: root
      password: ${mysql.password}

  mybatis:
    mapper-locations: mappers/*Mapper.xml
    configuration:
      map-underscore-to-camel-case: true
